### ISSUE TITLE
streamline menus

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#104]
- CASA structure
```
CASA
 - CASA 3
  - CASA 3.x
 - CASA 4
  - CASA 4.x
 - CASA 5
  - CASA 5.x
```
- "CANFAR" -> "AstroSoftware" or similar
- "Kill Session" and terminal(s) to 1st menu level
- Firefox to "Internet"
- gedit to "Accesories"

I also think Office and Multimedia are redundant and can probably be removed.

**Comment by yeunga** [comment]
Had a problem add 'CASA' submenu. Ended up with the following:
AstroSoftware -> CASA 3 -> CASA 3.x
                        -> CASA 4 -> CASA 4.x
                        -> CASA 5 -> CASA 5.x
