### ISSUE TITLE
demo.canfar.net getting stuck on "Establish session... (10 seconds)" pop up

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#106]
UI getting stuck on pop-up, reloading page connects user to their session.
[demo.canfar.net.zip](https://github.com/opencadc/arcade/files/5176169/demo.canfar.net.zip)

See https://cadc.slack.com/archives/C0177MVBP3Q/p1599054940011300 for context.

**Comment by brianmajor** [comment]
This is a symptom of issue #4 so closing.
