### ISSUE TITLE
Upgrade CARTA to v1.3.1

### ISSUE THREAD

**Issue by nbrunett** [opencadc/science-platform#112]
[This latest patch](https://github.com/CARTAvis/carta/releases/tag/v1.3.1) fixes some pretty commonly encountered bugs, especially one that results in CARTA crashing. I'm not certain but this may improve the stability around what was happening in #103 .

**Comment by nbrunett** [comment]
I'm sorry to move the target, but [v1.4](https://github.com/CARTAvis/carta/releases/tag/v1.4) was just released. It would be best to just get the latest version, in my opinion. Feel free to veto however.

**Comment by brianmajor** [comment]
Done
