### ISSUE TITLE
notebooks: start dir is /home/jovyan, not $HOME

### ISSUE THREAD

**Issue by brianmajor** [opencadc/science-platform#140]
Terminals in notebooks should open to $HOME (/cavern/home/<userid>)

**Comment by brianmajor** [comment]
Looks like this is still an open Jupyter lab issue and is not yet possible:

https://github.com/jupyterlab/jupyterlab/issues/1366

**Comment by chriswillott** [comment]
Yes, if I recall correctly what fixed it was adding a simple 'cd' to the default bashrc file when building the Docker image.

I have a file called global_bashrc that contains this (it also sets the prompt and activates the correct conda environment):
```
export PS1="${debian_chroot:+($debian_chroot)}\u@notebook:\w\$ "
# Enable conda and activate jwstdp by default
. "/opt/conda/etc/profile.d/conda.sh"
conda activate canucs0p5
cd

``` 

The Dockerfile has these lines:
```
# Add content to the global bashrc
COPY global_bashrc /home/jovyan
RUN cat /home/jovyan/global_bashrc >> /etc/bash.bashrc &&\
    rm /home/jovyan/global_bashrc

```

**Comment by sfabbro** [comment]
The "official" workaround for container images based on `jupyter/scipy-notebook` is to create a [startup hook script](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks) and place it it `/usr/local/bin/start-notebook.d/` , e.g.
```
#!/bin/bash
cd $HOME
```
That way the terminal will start in the `/arc/home/<user>` directory.

**Comment by BearBearCodes** [comment]
> The "official" workaround for container images based on `jupyter/scipy-notebook` is to create a [startup hook script](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks) and place it it `/usr/local/bin/start-notebook.d/` , e.g.
> 
> ```
> #!/bin/bash
> cd $HOME
> ```
> 
> That way the terminal will start in the `/arc/home/<user>` directory.

Hmm... I noticed you did this to get the `skaha-notebook:22.02` terminals to open in `/arc/home/<USER>`. Weirdly enough, if I copy your suggestion, my terminal starts in `/home/jovyan`.

**Comment by sfabbro** [comment]
Make sure your hook script is executable. You can also check the session logs.

**Comment by BearBearCodes** [comment]
Thanks, this solved it! After checking the [session logs](https://github.com/opencadc/skaha/tree/master/doc) and comparing the logs from my image to your `skaha-notebook` image, I noticed I was missing a line starting with:
```text
/usr/local/bin/start.sh: running hooks in /usr/local/bin/start-notebook.d
```
All I had to do was make the hook script executable, as you suggested. Thanks again!

**Comment by drtobybrown** [comment]
Is this fixed?

**Comment by brianmajor** [comment]
Yes, it is, thanks for the reminder.

**Comment by brianmajor** [comment]
Found that the solution I'd tested worked for a single container only, so not fixed yet.

**Comment by sfabbro** [comment]
The new [launcher script](https://github.com/opencadc/skaha/blob/master/deployment/k8s-config/kustomize/base/skaha-workload/config/start-jupyterlab.sh) does not work with the workaround mentioned above.

We would need to add two things:
- `cd $HOME` before launching the `jupyter lab` command
- re-add an environment variable (e.g. `NOTEBOOK_ARGS`) for users to pass extra options to the `jupyter lab` command in that script. For example users could pass `--debug` to trace what is going on at launch time, or another directory for the settings.
-

**Comment by brianmajor** [comment]
This has been addressed by https://github.com/opencadc/skaha/pull/311
