### ISSUE TITLE
Unable to find names for user groups

### ISSUE THREAD

**Issue by matthewbeaudoin** [opencadc/science-platform#171]
Upon opening a terminal in a JupyterLab environment (container image is `images.canfar.net/highz-alma/notebook-astropy:0.1`), the terminal prints the following output:
```
groups: cannot find name for group ID 753053001
groups: cannot find name for group ID 1025424273
groups: cannot find name for group ID 1477619040
I have no name!@skaha-notebook-mbeaudoin-wgywbhce-4mjhh:/home/jovyan$ 
```
Functionality of the terminal seems unaffected.

**Comment by brianmajor** [comment]
This happens there is an issue with platform operation.  Specifically, when the link to our access control service (that resolves group ids) is broken.
