### ISSUE TITLE
Feature Request: SSH support for git and GitHub

### ISSUE THREAD

**Issue by BearBearCodes** [opencadc/science-platform#223]
I would like to use git and GitHub to help manage my projects, but `openssh-client` is not installed in my container image (I'm using `notebook-scipy:0.2`). As a result, I can't generate ssh keys to link to my GitHub account (and HTTPS authentication seems to fail every time). Would it be possible to add `openssh-client` to this container?

**Comment by sfabbro** [comment]
`openssh-client` is actually installed on the [jupyter/minimal-notebook](https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile) which `jupyter/scipy-notebook` is based on.

**Comment by BearBearCodes** [comment]
I think the `skaha/notebook-scipy:0.2` image might have been built [before](https://github.com/jupyter/docker-stacks/blame/aa574accbd6d163c37daff49e77cf3a879d031f3/minimal-notebook/Dockerfile#L22) they added `openssh-client` to `jupyter/minimal-notebook`. None of the `ssh` commands work when I launch a notebook instance based on `notebook-scipy:0.2`.

An easy fix might be for the owner of `skaha/notebook-scipy` to regenerate the Docker image using the latest version of `jupyter/notebook-scipy`?

**Comment by sfabbro** [comment]
I just pushed a public skaha/skaha-notebook:22.02 which is an update of the noteboo-scipy and let the terminal start in the $HOME directory. Please test.

**Comment by BearBearCodes** [comment]
I can confirm `skaha-notebook:22.02` works with `ssh` and starts terminals in my home directory. Thanks!
