### ISSUE TITLE
Integrate ADMIT

### ISSUE THREAD

**Issue by brianmajor** [opencadc/science-platform#25]

**Comment by yeunga** [comment]
Installed ADMIT from CASA version 4.5.x to 5.6.1-8 (the latest version at time of writing). Tried installing ADMIT to versions below 4.5.0, found that some installations failed. According to http://admit.astro.umd.edu/installguide.html, ADMIT should work with versions 4.5 and up. 

During installation of ADMIT, found that Sphinx was needed by ADMIT to build documentation and Graphviz provided dot which was needed to diagram flows. So updated Dockerfile to install Sphinx and Graphviz as well.

During testing of ADMIT, found that /opt/admit/bin/admit used /bin/csh, so added installation of tcsh to the Dockerfile.

Before using ADMIT, one needs to 'source /opt/admit/admit_start.sh' to set up the working environment for ADMIT. This source statement was added to startup.sh which is executed when the CASA terminal is initiated.

To test the ADMIT package:
1. Start a CASA container (any version from 4.5.x and up)
2. In the bash terminal, enter "admit". Information on the ADMIT package should be display. For example:
cwd: ~
 > admit
ADMIT        = /opt/admit
    version  = 1.0.8.2
CASA_PATH   = /opt/casa-pipeline-release-5.6.1-8.el6 linux admit casa-5.6.1-8-cadcauthtest2-xgb7nwaf-of9pxxp8-chsbh
CASA_ROOT    = /opt/casa-pipeline-release-5.6.1-8.el6
    prefix   = /opt/casa-pipeline-release-5.6.1-8.el6
    version  = release-pipeline-5.6.1-8
    revision = 1
3. Start up casa
4. Within casa, enter "import admit". Should see no error. In some later CASA versions, may see the following warning message which is generated as a result of missing the asap package. This warning can be safely ignored. Please refer to https://github.com/astroumd/admit/issues/36
