### ISSUE TITLE
Provide warning when sessions die after 14 days

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#258]

**Comment by sfabbro** [comment]
Could be useful to show some kind of timer of "time left in the session"

**Comment by brianmajor** [comment]
Added my thumbs up on this on behalf of another user who was caught by this.

**Comment by ijiraq** [comment]
Could we email users after 7 and 10 days to tell them the session was expiring?  This could be a crontab that runs outside the platform, checks all running sessions, grabs the ones that only have x days left, and emails the owner to warn them. 

To complete the journey each session on the Science Portal page needs a button called 'extend' that would set the expiration date 14 days forward.  This would allow you to keep your session alive by actively going to it.

**Comment by brianmajor** [comment]
The current idea is to show the session expiry time on the portal page.  Beside it will be a 'keep alive' button to extend the expiry time.

**Comment by brianmajor** [comment]
Session renewal support is complete, and session lifetime is now much shorter.  If email functionality is still desirable, please comment here and we'll open a new issue.
