### ISSUE TITLE
Show cluster health stats on the session launch page

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#259]

**Comment by sfabbro** [comment]
To help us write full development stories, this is the discussion on the user-facing part of load monitoring.

The idea of this feature would be for users to quickly acquire knowledge on their usage and the global health of the available resources.
The minimal display could include several indicators as described below, with an automated refresh rate of 2min or on-demand. Each display could include the total allowed by quota if quotas are enforced.

When users are logged in, they should have direct access to the display of:
- the number of headless sessions and their states (Starting/Pending...)
- the number of cores used by all their running containers
- the number of GPUs being used
- the total number of cores currently in used in the total cluster and the total number available
- we need a useful indicator of RAM. A suggestion would be the maximum RAM node available
- same for GPU memory.

This feature request is geared towards a browser display, but access to a API to make queries would also be useful.

Please comment!

**Comment by drtobybrown** [comment]
How expensive is it to refresh? I think it would be good to have it constantly updating. Also the the number _and_ percentage or fraction of the total available (we still don't have autoscaling right?) would be useful for these quantities.

**Comment by sfabbro** [comment]
Unsure how intensive we can be on the refresh. Part of the story will be to come up with a reasonable refresh rate.
No autoscaling yet.

**Comment by drtobybrown** [comment]
Graphical monitoring would be nice...

**Comment by fraserw** [comment]
I think a simpler presentation could be # of cores used / number of cores available per node. Similarly for memory.

Then a summary of cores available at the bottom.

A similar presentation of # of migs in use (this is the same as number of launchable jobs as CADC doesn’t allow multiple MIG use yet). 

This is essentially all the info I as a user would care about. Other things like jobs status would be noise in the every day usage.

**Comment by at88mph** [comment]
It sounds like we want a Dashboard for users to sign in and be presented with.  In fact, this sounds an awful lot like the existing OpenStack Dashboard:

![OpenStack-Dashboard](https://user-images.githubusercontent.com/1671908/185492847-36339da6-5b21-48f0-a666-bf7b7ea685eb.png)

**Comment by sfabbro** [comment]
Or directly into the notebook for a given session, such as in Google Colab:
![image](https://user-images.githubusercontent.com/1484206/185493684-8250c7b1-2b01-4f27-97ed-c46876f8ba43.png)

This could be done with a JupyterLab extension, but would require ensuring the requested metrics are available.

**Comment by brianmajor** [comment]
A simple version of this is now available on the platform.  We'll be looking at more detailed views, perhaps from grafana and prometheus, next.
