### ISSUE TITLE
log session meta data (type, number, date-time, duration) and failed session requests

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#262]

**Comment by sfabbro** [comment]
@kcasteels is this something we could plan on exposing to the users with the metric aggregation system?

**Comment by brianmajor** [comment]
@drtobybrown Other than 'failed session requests', I think most of this has been covered now by the recent changes in the portal.  Am I reading the title of this correctly?

**Comment by drtobybrown** [comment]
Yep - happy to close if you like

**Comment by brianmajor** [comment]
Okay thanks, will do.  We have an internal task for improving error reporting which should cover the part about failed sessions.
