### ISSUE TITLE
Unable to launch multiple jobs in parallel

### ISSUE THREAD

**Issue by shinybrar** [opencadc/science-platform#270]
# Ten words or less
Launching multiple jobs with the same authentication fails.

# Details
@brianmajor We are currently have an operational open-source python wrapper for `skaha` which is available here: 

https://github.com/CHIMEFRB/skaha

Working with single sessions works as expected, however when using the same ssl client to launch multiple jobs in parallel, we get the following error:
```
 'dh13nm3x',
 'unexpected exception: java.io.IOException: Error executing command: [kubectl, --namespace, skaha-workload, create, secret, docker-registry, harbor-secret-shinybrar, --docker-server=images.canfar.net, --docker-username=shinybrar, --docker-password=J? ???G?1] Error: Error from server (AlreadyExists): secrets "harbor-secret-shinybrar" already exists']
 'unexpected exception: java.io.IOException: Error executing command: [kubectl, --namespace, skaha-workload, create, secret, docker-registry, harbor-secret-shinybrar, --docker-server=images.canfar.net, --docker-username=shinybrar, --docker-password=J? ???G?1] Error: Error from server (AlreadyExists): secrets "harbor-secret-shinybrar" already exists']
 'unexpected exception: java.io.IOException: Error executing command: [kubectl, --namespace, skaha-workload, create, secret, docker-registry, harbor-secret-shinybrar, --docker-server=images.canfar.net, --docker-username=shinybrar, --docker-password=J? ???G?1] Error: Error from server (AlreadyExists): secrets "harbor-secret-shinybrar" already exists']
 ```
In this case we were launch 4 jobs in parallel, the first one succeeded, however every subsequent job failed. 

Underneath the hood we are just calling the `/POST` url for skaha with the same authentication context.

# Expected Behaviour
Ideally, skaha should at least let you execute multiple, up to a certain maximum (128?) of requests in parallel.

**Comment by brianmajor** [comment]
Hi @shinybrar  Okay, this is a bug and we'll get to it ASAP.  Thanks for reporting.

**Comment by brianmajor** [comment]
There is clearly an issue with the service which we will fix.  But also, as you can see in your log message, the password is full of odd characters.  This happens when harbor (images.canfar.net) 'invalidates' CLI Secrets (passwords) due to expiry.  We are working on that bug separately (and actively), but you may have some immediate success if you login (using the shinybrar account) to harbor and update your CLI Secret under the User Profile in the top right corner.

Will still get a fix out for the bug, probably today.

**Comment by shinybrar** [comment]
@brianmajor 
I can confirm the problem still exists after changing the CLI Secret. 

```
'unexpected exception: java.io.IOException: Error executing command: [kubectl, --namespace, skaha-workload, create, secret, docker-registry, harbor-secret-shinybrar, --docker-server=images.canfar.net, --docker-username=shinybrar, --docker-password=<REDACTED>] Error: Error from server (AlreadyExists): secrets "harbor-secret-shinybrar" already exists',
```

In this instance, the REDACTED password was my alphanumeric CLI secret, without any special characters.
