### ISSUE TITLE
fine grained selection of session resources

### ISSUE THREAD

**Issue by sfabbro** [opencadc/science-platform#288]
Currently the session resources are limited by the lowest available resources (CPUs, RAM, ephemeral, GPUs)  on the hardware nodes to avoid bad scheduling.

This is a feature request to implement more fine grained selection of resources, which could allow larger resource sessions, even if not always available.

**Comment by brianmajor** [comment]
I have some ideas on how this can be done that I would like to explore.  It
basically involves a short negotiation with skaha--client requests a
certain amount of resources and skaha responds with what it can give, which
may be more, less, or the same as the request.

**Comment by brianmajor** [comment]
A very simple change to add more options to the selections has been made.  In the future we'll look at making those options reflect the current state of the cluster.
