### ISSUE TITLE
desktop session: UI for RAM request when start software container

### ISSUE THREAD

**Issue by helenkirk** [opencadc/science-platform#325]
This suggestion for development is prompted by a specific scenario I just ran into during testing the Starlink container.  There is at least one known use case for Starlink containers which can require gobs of RAM (up to 100GB) - this is when making maps from SCUBA-2 data.  The map-maker will crash with a core dump if there is less RAM available than it needs.  In order for someone to stably run the SCUBA-2 mapmaker, there would need to be a mechanism for them to specify that their particular starlink container would need to be guaranteed access to some specified amount of RAM.  NB that many other uses of Starlink do not require such high amounts of RAM, so you wouldn't want to always be allocating such a large amount; it would make the most sense to have a mechanism for the user to request the amount of RAM they need when launching the Starlink container.

**Comment by brianmajor** [comment]
During ALMA platform meeting it was suggested that, for each item in the 'Astro Software' menu, a sub menu be presented that is the list of options for the memory requirements of that item.  Perhaps 8Gb, 32Gb, and 64Gb.

**Comment by brianmajor** [comment]
I would like to comment that this issue has been raised again as being critical for ALMA data reduction.
