### ISSUE TITLE
update leap second table for CASA

### ISSUE THREAD

**Issue by helenkirk** [opencadc/science-platform#33]
Often when running CASA, a non-fatal error message comes up that says something like this: "Leap second table TAI_UTC seems out of date...."

While probably not generally a problem, it sounds like it may be fairly easy to fix, although the ideal fix requires a short process to run any time that a new CASA terminal/process is initiated. (The leap second table is not calculated very far into the future, so it becomes out of date every few months.)  There are two different recommended routes for making the update.:
For (at least) the older versions of CASA (4.2.2 and older), the following is supposed to work:
> cd [casa directory]/data
> rsync -avz rsync://casa-rsync.nrao.edu/casa-data .
reference: https://casaguides.nrao.edu/index.php?title=Fixing_out_of_date_TAI_UTC_tables_%28missing_information_on_leap_seconds%29

For CASA versions later than 4.4, the following should work:
> casa-config --exec update-data

For earlier CASA versions, the above command may work if a patch is first downloaded from https://svn.cv.nrao.edu/casa/distro/patches/update-rsync-url/update-data.patch
and the following command is then run:
>   $ update-data.patch <PATH-TO-CASA-DISTRIBUTION>

reference for these latter two procedures: https://casaguides.nrao.edu/index.php/Updating_the_CASA_Data_Repository

**Comment by brianmajor** [comment]
More on this from Gerald Schieven:

I’m getting “Leap second tale TAI_UTC seems out of date” severe errors in casa.  The recommended fix is to run the perl script “update-data” within casa.  However, this does not seem to be installed with the casa-5.6.1-8 container.  The casa knowledgebase article about this is at:
 https://help.almascience.org/index.php?/Knowledgebase/Article/View/300/0/HowcanIupdatethedatarepositorycopyofmyCASAinstallation

**Comment by yeunga** [comment]
Referring to https://casaguides.nrao.edu/index.php/Updating_the_CASA_Data_Repository, for CASA versions
- 4.4 and 4.5: 'casa-config' is missing. 
- 4.6.0: '!update-data' and 'casa-config --exec update-data' work
- 4.7.0 to 5.6.1-8 (latest version at time of writing): update-data is missing, so '!update-data' and 'casa-config' fail.

'update-data.patch <PATH-TO-CASA-DISTRIBUTION> works for all CASA versions. However this patch method is supposed to be used for CASA versions 4.4 or earlier. Will check with CASA to find out if 'update-data.patch' is functionally equivalent to 'casa-config'. For now, all CASA versions are built with 'update-data.patch' executed in startup.sh.

**Comment by yeunga** [comment]
Submitted a ticket to NRAO to check if 'update-data.patch' is equivalent to 'casa-config'. Will reopen this ticket if not.

**Comment by helenkirk** [comment]
I've just run into this error message again for a casa4.7.2 container launched not even an hour ago.  My recollection was that we'd earlier tested & verified that Alinga's fix was working for all casa containers, so I'm not sure what's going on here.

**Comment by brianmajor** [comment]
Hi Helen.  Alinga can take a look and hopefully see what's going on.

**Comment by helenkirk** [comment]
Thanks, Brian, and thanks in advance, Alinga!  As an update, I am trying a related dataset today, this one on the casa4.7.0 container and I get the same leapsecond error message.  So the issue does not appear to be confined to a single casa container.

**Comment by drtobybrown** [comment]
@brianmajor can we set the update script to run as a kron job?

**Comment by brianmajor** [comment]
Hi Toby.  Yes, I created (an internal) task to do just that today.

**Comment by severingaudet** [comment]
The command to run is: `rsync -avz rsync://casa-rsync.nrao.edu/casa-data /arc/projects/casa-data-repository/`
I have run it today and the leap second issue should now be fixed.

In the longer term, the /arc/projects/casa-data-repository should be owned by someone other than me and be writable by a casa maintainers group. Anyone in that group could set up a cron jos to execute the above command daily.
