### ISSUE TITLE
enhancement: enable font increase in desktop containers

### ISSUE THREAD

**Issue by helenkirk** [opencadc/science-platform#349]
This is a request from SaraE to have a straightforward way for users to increase the font size of the text displayed within software containers (e.g., CASA) within the desktop environment for better readability.

**Comment by brianmajor** [comment]
Hi @helenkirk  -  I googled this and (amazingly) there's a pretty simple way to change the font size on xterms and it seems to work in arcade desktop windows.  With the window selected, hold the control key down while you right click with your mouse.  A menu appears by your mouse with a number of font size options.

**Comment by helenkirk** [comment]
Thanks, @brianmajor !  I'll pass that tip along.
