### ISSUE TITLE
New jlab terminals don't source .bashrc when opened

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#364]
from https://github.com/jupyterlab/jupyterlab/issues/489

> it appears to be fixed now by specifying SHELL=/bin/bash when starting JLab.

**Comment by sfabbro** [comment]
This is set at the container build time. Which container image are you referring to?

**Comment by drtobybrown** [comment]
Astroml

**Comment by sfabbro** [comment]
it is working here fine. are you sure you have a  ~/.profile file ? if not, copy an example from your `/arc` home directory from the container OS, i.e. :  `cp /etc/skel/.profile ~/`

**Comment by brianmajor** [comment]
Has this been resolved Toby?

**Comment by drtobybrown** [comment]
Yes I think so
