### ISSUE TITLE
Show current directory size in /arc

### ISSUE THREAD

**Issue by brianmajor** [opencadc/science-platform#390]
Show the current size of directories in the /arc file system.  Currently this is only available in /vault.  This is needed so that users know how close they are to their quotas.

**Comment by at88mph** [comment]
If the issue is quota notification, the current quota is displayed in the UI:
![Screenshot from 2024-11-26 14-51-01](https://github.com/user-attachments/assets/89ecef9a-9e59-42cf-9270-e267389a41d5)

**Comment by at88mph** [comment]
Closing for now, but reopen if still needed.
