### ISSUE TITLE
[FEAT] DockerHub Registry Support

### ISSUE THREAD

**Issue by shinybrar** [opencadc/science-platform#398]
In addition to the Harbor Container Registry hosted at `images.canfar.net` we should enable support for `docker.io/library` as a registry server. 

## Benefits
- Dockerhub is ubiquitous and used widely, this removed the overhead to upload and manage container images at CANFAR.

## Drawbacks
- We can potentially open up CANFAR to to malicous code, especially if people are not careful, potentially we can allow certain repositories to be pulled from docker hub, e.g. `chimefrb/xxxxx` would work, but `google/something` would not.

**Comment by brianmajor** [comment]
I like this idea and your suggestion about limiting it to certain dockerhub repos.  I guess you as the owner of that repo can control who pushes images there?

Also, as you mentioned in our meeting, there's the problem with the type labels.  A couple of thoughts from me on the labels:

- They essentially identify the category of how images are to be started and a few other details.
- We would like to associate other metadata (like a description of the image for example) with images, but that functionality isn't available in harbor.

So, I am wondering (in parallel to this conversation) whether having the labels in harbor is the right place for them, or if another concept can replace them.  But regardless it's something we need to work out before adopting dockerhub.

**Comment by shinybrar** [comment]
After doing some overnight thinking, I have the following questions / concerns.

1. Allowing `DockerHub` containers would significantly increase the bandwidth requirement to the cluster. Is this an acceptable solution?
2. How does the Science Platform actually choose a deployment strategy:
    - Do we download the image on the target node first, look at the `label` and then spawn the container
    - Do we look at the label information apriori via an API, and then provide a deployment strategy to 
3. I believe the problem is actually the usability of Harbor rather than anything else. If we can even get permanent `CLI Secrets` or an API/CLI way to label and interact with our images on CANFAR that would go a long way.

**Comment by shinybrar** [comment]
Tracking in #427 now.
