### ISSUE TITLE
Request for 'Midnight Commander' (mc) installation 

### ISSUE THREAD

**Issue by hossteim** [opencadc/science-platform#402]
I wanted to install and use Midnight Commander (mc) in the terminal in the Science Portal. It needs "sudo" permission to run “apt install mc -y” for the installation.

**Comment by brianmajor** [comment]
HI @hossteim - It the idea that you would use it to work with files in /arc?  There are a few places we could put it:  in the terminal, in the desktop itself, or as a new container in the AstroSoftware menu.  Perhaps because it is a common tool the terminal is the best place.

**Comment by brianmajor** [comment]
Now available on version 1.1.2 of the terminal from the desktop session.
