### ISSUE TITLE
Install svn

### ISSUE THREAD

**Issue by shionandrew** [opencadc/science-platform#414]
Could `svn` be installed on the desktop sessions of canfar? `Git` is currently installed, but `svn` is not.

**Comment by brianmajor** [comment]
Yes, thanks, we'll be adding `svn` soon.

**Comment by shinybrar** [comment]
@shionandrew If this is regarding getting difxcalc working on CANFAR containers -- look at `chimefrb/baseband-analysis` Issue 418.

**Comment by brianmajor** [comment]
Hi @shinybrar I can't find `baseband-analysis` in the `chimefrb` organization.  Anyhow, no, it's not related to difxcalc, though I'd be interested in hearing if this is a problem we're about to run into!
