### ISSUE TITLE
container hostnames are not user friendly

### ISSUE THREAD

**Issue by brianmajor** [opencadc/science-platform#42]
Typing `hostname`, or using `\h` in bash prompt config displays the container hostname.  Hostnames are currently in the format:  arcade-<userid>-<sessionid>-<containerid> and are not what we want users to see.  They should simply state the name and version of the software.

**Comment by drtobybrown** [comment]
hostnames are also unfriendly and long in the terminal and xterm containers

**Comment by brianmajor** [comment]
The hostnames are now short and either match the session name provided on launch, or the name of the app, such as `casa-4-5-6`.  If some tweaks are needed we can reopen this and make the alterations.
