### ISSUE TITLE
A simple user driven process for adding new users to the science platfrom

### ISSUE THREAD

**Issue by ijiraq** [opencadc/science-platform#425]
Once a person has a CADC account an admin of a resource would have the capability  to add that user to the science platform and allocate them resources that they admin,  without the need to connect with an admin inside CANFAR/CADC.

**Comment by brianmajor** [comment]
I like this idea, and when we have groups representing the projects, then the owner and admins of the groups would just add and remove users.
I guess for non-project/independent users the current allocation process would remain.

**Comment by brianmajor** [comment]
Work is Complete
