### ISSUE TITLE
reduce core allocation for desktop session

### ISSUE THREAD

**Issue by helenkirk** [opencadc/science-platform#441]
(This got suggested by JJ at the ALMA CANFAR meeting this morning.)  We should reduce the default core allocation for a desktop session to 1 from 2.  Most of the processes which get run on a desktop session are from containers launched within the desktop (e.g., casa containers, terminals, etc).  So very little, basically just firefox and gedit, actually use that initial 'desktop session' 2 core 16GB allocation, and most of the allocation is sitting idle.  Let's free it up to use for other things!  JJ and Kevin also discussed whether multiple desktop sessions could be run on the same core, and Kevin thought it should be possible in principle (though perhaps the small compute gains make this a lower priority to look into).

**Comment by brianmajor** [comment]
This is a good idea.  I had actually thought we were using less in the Desktop but we are indeed using 2 cores and 16 GB RAM.  Let's change cores to 1 as you suggest.  Anyone have an idea of how much RAM would be needed by a NoVNC session?  8 GB?

**Comment by sfabbro** [comment]
For the RAM requirements, isn't it something we could actually check in the current session @kcasteels  ?

**Comment by brianmajor** [comment]
Good idea.  I've taken a quick look and none are using more than 500 MB.

**Comment by brianmajor** [comment]
This change has been made.  Please reopen or comment if any issues are seen.
