### ISSUE TITLE
Feature request: get rid of the annoying autocomplete boop

### ISSUE THREAD

**Issue by fraserw** [opencadc/science-platform#512]
The sound is grating at best, infuriating at worst. Can it be silenced? As far as I know there is no way to have a certain URL auto muted in common browsers, requiring users to remember to mute the tab manually.

**Comment by ijiraq** [comment]
this is  a shell configuration setting `xset -b` to disable the sound.

so. in the terminal type `xset -b` or 

 `echo xset -b >> ${HOME}/.bashrc`

to have off by default.

**Comment by fraserw** [comment]
set -b does not disable sound in an arcades terminal.
