### ISSUE TITLE
Terminal emulator vs. xterm 

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#55]
It should be clear which the user should use. If it's the Terminal emulator, it needs to default to home.

**Comment by drtobybrown** [comment]
If the choice is up to the user, can we make sure all tools are available to both?

**Comment by brianmajor** [comment]
We are planning on renaming 'xterm' to 'python tools' (or something similar) and making the local terminal more functional.

**Comment by drtobybrown** [comment]
Got it

**Comment by drtobybrown** [comment]
@brianmajor @yeunga I think there are other non-python use cases for the "python" container (e.g., vsync/vcp). Perhaps there's a more representative name that would suit? I didn't have a problem with xterm myself.

I think the broader issue is around the divergent software packages available to terminal and python containers... This stops a user picking their favorite and sticking with it. For example, to run gedit from the command line requires terminal, while vcp requires "python".

**Comment by brianmajor** [comment]
I'm not particularly fond of 'python' either.  We switched away from 'xterm' to avoid mixup with the local terminal emulator.  

The container really is a collection of python client tools for interacting with the CADC/CANFAR and other sites that support VO protocols.  vcp, cadc-tap, cadc-get-cert, etc... 

Perhaps gedit should have a launch icon on the desktop to make it more visible?  It technically not possible to launch gedit from the 'python' window.

I agree that, whatever we call it, it should be thing users go to for common tools.

**Comment by drtobybrown** [comment]
I think xterm is less confusing that python. It would also be good to have the icon next to "Terminal emulator" so the user knows they can/should choose both.

> The container really is a collection of python client tools for interacting with the CADC/CANFAR and other sites that support VO protocols. vcp, cadc-tap, cadc-get-cert, etc...

Can we get these tools accessible to the Terminal Emulator as well?

**Comment by yeunga** [comment]
Here's the plan to address this issue:
- rename ‘python’ back to ‘xterm’
- make sure that there’s an xterm icon on the desktop
- make sure that there isn’t a terminal emulator icon on the desktop
- rename the terminal emulator from the drop-down menu to xterm
- add xterm icon in drop-down menu (where terminal emulator now is)
- ensure there’s a gedit icon on the desktop and in the drop-down menu

**Comment by yeunga** [comment]
A new version of "Terminal" container has been released. This container is based on ubuntu20.04 and is equipped with anaconda and astroconda among other cadc packages.
