### ISSUE TITLE
don't have astropy and pyfits

### ISSUE THREAD

**Issue by DazhiZhou** [opencadc/science-platform#568]
Hi, actually I was trying to run some scripts with casa 6.6. However, I cannot run it as it requires the module pyfits and astropy. And somehow I cannot use 'pip3 install pyfits --user' to install corresponding module to solve the problem, as it still tells me that I don't have the relevant module... Can you help me figure out the problem? Many thanks

**Comment by helenkirk** [comment]
Hi Dazhi, thanks for noting this.  I'll look into getting this addressed, but it may not be until early next week.  Unfortunately the internet is mostly down in my office today (I'm on a mobile hot-spot) and container rebuilding & testing probably needs more bandwidth than available through that.  In the short-term, can I suggest you try casa6.5.6 instead?  I think the warning message you are seeing is one that I only noticed for a recent fix of a casa.6.6.0 container, so the version prior is hopefully okay.

**Comment by DazhiZhou** [comment]
Dear Helen,

Thank you very much for your great effort! And sorry for my late reply. There is a very frequent blackout here. I think currently I am fine with the 6.5.6. 

Wish you a nice long weekend
Dazhi

**Comment by helenkirk** [comment]
Thanks, Dazhi.  We're still waiting for the internet repairs to finish in the office here, so the 6.6.0 container work is still on hold.  I'm really glad that 6.5.6 works fine for your purposes in the meantime.
Hope you had a good long weekend too,
Helen

**Comment by DazhiZhou** [comment]
Many thanks again! Yes, so far so good.

Cheers
Dazhi

**Comment by helenkirk** [comment]
Hi Dazhi,

This is a long-awaited follow-up, but with some help from the CASA developers, the astropy library issue has *finally* been solved for CASA 6.6* versions.  CASA 6.6.0 and CASA6.6.3 are now both available and properly functioning within the Desktop environment.

Thanks again for reaching out and reporting this issue!
