### ISSUE TITLE
broken doc url in main readme

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#598]
https://github.com/opencadc/science-containers/blob/main/doc in the following markdown gives 404 not found so should be updated

**CANFAR Science Portal Documentation**

User documentation for the CANFAR Science Portal and Platform can be found here: [Science Portal Documentation](https://github.com/opencadc/science-containers/blob/main/doc)

**Comment by brianmajor** [comment]
Thanks for reporting @drtobybrown.  Where is that page with the broken link exactly?

**Comment by drtobybrown** [comment]
Yep it's in [the readme here.](https://github.com/opencadc/science-platform/blob/master/README.md)

There are a couple of other broken links on that page too. (https://github.com/opencadc/science-containers/blob/main/containers)

**Comment by brianmajor** [comment]
Fixed.  Thanks again.
