### ISSUE TITLE
Fail to start message bus

### ISSUE THREAD

**Issue by yeunga** [opencadc/science-platform#61]
The message bus fails when CASA starts up. The following message is displayed:

"Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
warning: dbus is not properly configured, viewer scripting will not be available
Unable to start viewer, maybe no dbus available?"

The following CASA versions are affected:
34.0.19988-002-64b
40.0.22208-002-64b
40.1.22889-003-64b
41.0.24668-001-64b-2

**Comment by brianmajor** [comment]
Moved to canfar/arcade
