### ISSUE TITLE
More informative first start window

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#64]
I think for new users, the following pop up isn't very helpful. How would they know what a panel is or what it should look like?

Perhaps, load the default and then link to docs on how it can be changed?
![Screenshot 2020-06-17 at 14 44 33](https://user-images.githubusercontent.com/6336385/84937104-457cf480-b0a9-11ea-8263-a5f60ec7365a.png)

**Comment by yeunga** [comment]
This problem resulted from changing $HOME to /cavern/home/<user id> causing UI related files to be stored in $HOME. The problem has been fixed by using $XDG_CONFIG_HOME for UI related files.
