### ISSUE TITLE
Blank panel icons on start up

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#65]
![Screenshot 2020-06-17 at 14 46 34](https://user-images.githubusercontent.com/6336385/84937240-72310c00-b0a9-11ea-88a5-1aa3e6a96823.png)

**Comment by yeunga** [comment]
This problem resulted from changing $HOME to /cavern/home/<user id> causing UI to be set up incorrectly. This problem has been fixed by using XDG_CONFIG_HOME instead of $HOME for display related files.
