### ISSUE TITLE
plotms & proc dbus error

### ISSUE THREAD

**Issue by helenkirk** [opencadc/science-platform#70]
In most, but not quite all, implementations of casa5*, running the 'plotms' command, which pulls up an interactive graphical interface window, generates an error message when exiting casa which looks something like this:
20-06-17 00:15:02 => proc dbus is being killed
[with the date & time obviously varying with when the process is being run]

This error message appears to be generated for every casa5* container _except_ the following:
5.1.2 (pipeline mode only)
5.4.0-70 (non-pipeline mode)
5.4.2-8 (non-pipeline mode)
5.6.1-8 (non-pipeline or pipeline mode)

I didn't notice any problematic behaviour within the plotms graphics window, so I'm not sure what impact this error message has on the user-side.

**Comment by brianmajor** [comment]
moved to canfar/arcade
