### ISSUE TITLE
Terminal not running .bashrc on startup

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#75]
My .bashrc is in /cavern/home/thbrown and is run by xterm on startup. However when I start terminal, it doesn't find it, even when I cd into my home dir.

I have to source /cavern/home/thbrown/.bashrc manually

<img width="1440" alt="Screenshot 2020-07-21 at 12 53 23" src="https://user-images.githubusercontent.com/6336385/88100305-3a5a3000-cb51-11ea-8bf3-2330d2dbf32b.png">

**Comment by yeunga** [comment]
Since the new terminal now starts in the user's home directory, .bashrc is run on startup.
