### ISSUE TITLE
Naming suggestion: 'Terminate' to 'exit' or 'end'

### ISSUE THREAD

**Issue by heh15** [opencadc/science-platform#79]
I log into Arcade and try to open a terminal. I didn't read carefully and click the button 'terminate' since 'terminate' looks similar to 'terminal'. I feel it would be better to change that option name to 'end' or 'exit' or 'logout' to avoid confusion.

**Comment by yeunga** [comment]
Rename terminate to "kill session". However it is not easy to insert a prompt "do you really want to do this?"

**Comment by drtobybrown** [comment]
This is done right?

**Comment by yeunga** [comment]
Yes, this is done. It has been renamed to "kill session".
