### ISSUE TITLE
addition of image viewer

### ISSUE THREAD

**Issue by nbrunett** [opencadc/science-platform#84]
It looks like the only way to view image files likes PNG, PDF, etc. is through Firefox. Could a image viewer be added?

**Comment by yeunga** [comment]
This image view is to be available in the new terminal? Would you have any preferred image viewer, e.g. https://itsfoss.com/image-viewers-linux/?

**Comment by nbrunett** [comment]
My biggest use case would be double-clicking the image file in the file explorer GUI and have it pop up in some display window. Being able to also launch this from a CLI would probably be handy, but it's not my personal priority.

I don't have a preference for the viewer app.

**Comment by yeunga** [comment]
Added gimp to both arcade desktop and the new terminal container. On arcade desktop, gimp is available under Applications -> Graphics -> GNU Image Manipulation Program
