### ISSUE TITLE
Feature request: Install git command in Arcade terminal

### ISSUE THREAD

**Issue by heh15** [opencadc/science-platform#88]
I would like to transfer some of my scripts into Arcade. It would be nice if I can clone my scripts from my git repo. That way I can easily keep my scripts in Arcade updated.

**Comment by drtobybrown** [comment]
Git commands are available in the xterm container. 

The terminal emulator will be removed soon to simplify the ARCADE workflow

**Comment by heh15** [comment]
How should I open the xterm container?

**Comment by drtobybrown** [comment]
Applications -> CANFAR -> xterm

**Comment by yeunga** [comment]
git is available in the new terminal.
