### ISSUE TITLE
Change the background color of the xterm terminal from white to black

### ISSUE THREAD

**Issue by heh15** [opencadc/science-platform#89]
I opened the xterm and it has white background with black letters. I want to change the default to have black background wth light grey letters. I tried to add the following lines in '.Xresources' file.  

```
xterm*background: black
xterm*foreground: lightgray
```

But the background does not change. I also tried to run the following command to feed the change

`xrdb ~/.Xresources`

However, it gives me the error
`bash: xrdb: command not found`

I was wondering if there's a way to achieve the goal.

**Comment by drtobybrown** [comment]
`xterm -fg white -bg black`

**Comment by yeunga** [comment]
Thanks Toby. Updated startup script to start xterm with the above options.
