### ISSUE TITLE
Feature request: Copy the text from local computer to Arcade

### ISSUE THREAD

**Issue by heh15** [opencadc/science-platform#90]
The load speed of webpage in Arcade is slow compared to that in local computer. I feel it is more convenient to search something, such as a code issue, in the browser of my local computer. After that, I would like to copy the solution into my Arcade terminal. Currently I can't do that. Is that possible to achieve that function?

**Comment by drtobybrown** [comment]
There's a copy/paste functionality for ARCADE. The tutorial is here - https://github.com/opencadc/arcade/blob/master/arcade-tutorial/Clipboard_Tutorial.pdf

Is this what you're referring to?

**Comment by heh15** [comment]
Thanks, Toby! That's what I am looking for. I didn't notice there's a tutorial folder in the repo. I will pay more attention to it.

**Comment by drtobybrown** [comment]
Can we close this?
