### ISSUE TITLE
Exiting xterm with Ctrl+D stops the application being reopened

### ISSUE THREAD

**Issue by drtobybrown** [opencadc/science-platform#95]
reproduce the issue.

- Ctrl+D closes xterm

- xterm and python (is this still just re-badged xterm?) applications don’t re-open after 2+ minutes at least

**Comment by yeunga** [comment]
Tried it out on the new terminal. 
- open a terminal
- press Ctl-D which closed the terminal
- open another terminal
The 2nd terminal opens within seconds.
